language: cpp
compiler:
    - clang++
    - g++
os:
    - osx
    - linux
addons:
    apt:
        packages:
            - cmake
before_script:
    - cmake --version
    - $CXX --version
script:
    - cmake
    - make -j 2
    - make test
